[deps]
ClimaAtmos = "b2c96348-7fb7-4fe0-8da9-78d88439e717"
ClimaComms = "3a4d1b5c-c61d-41fd-a00a-5873ba7a1b0d"
ClimaCoupler = "4ade58fe-a8da-486c-bd89-46df092ec0c7"
ClimaLand = "08f4d4ce-cf43-44bb-ad95-9d2d5f413532"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[sources]
ClimaAtmos = {path = "../../packages/ClimaAtmos"}
ClimaComms = {path = "../../packages/ClimaComms"}
ClimaCoupler = {path = "../../packages/ClimaCoupler"}
ClimaLand = {path = "../../packages/ClimaLand"}
