[deps]
ClimaAnalysis = "29b5916a-a76c-4e73-9657-3c8fd22e65e6"
ClimaAtmos = "b2c96348-7fb7-4fe0-8da9-78d88439e717"
ClimaComms = "3a4d1b5c-c61d-41fd-a00a-5873ba7a1b0d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[sources]
ClimaAnalysis = {path = "../../packages/ClimaAnalysis"}
ClimaAtmos = {path = "../../packages/ClimaAtmos"}
ClimaComms = {path = "../../packages/ClimaComms"}
